# Generated by Django 5.1.1 on 2024-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
            ],
        ),
    ]
